apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: istio-system
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: istio-ingressgateway
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 10.64.140.45
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80